FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["BakeItCountApi.sln", "./"]
COPY ["BakeItCountWeb/BakeItCountWeb.csproj", "BakeItCountWeb/"]

RUN dotnet restore "BakeItCountWeb/BakeItCountWeb.csproj"

COPY . .

WORKDIR "/src/BakeItCountWeb"
RUN dotnet build "BakeItCountWeb.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BakeItCountWeb.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "BakeItCountWeb.dll"]