// <auto-generated />
using System;
using BakeItCountApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BakeItCountApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250926133554_FixPairId")]
    partial class FixPairId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BakeItCountApi.Cn.Achievements.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AchievementId");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementId = 1,
                            Criteria = "Comprar 1 bolo",
                            Description = "Comprou seu primeiro bolo. Volte sempre :)",
                            Name = "Primeiro Delícia"
                        },
                        new
                        {
                            AchievementId = 2,
                            Criteria = "Comprar 3 bolos de chocolate",
                            Description = "Três bolos de chocolate?",
                            Name = "Connoisseur do Chocolate"
                        },
                        new
                        {
                            AchievementId = 3,
                            Criteria = "Comprar 5 bolos premium",
                            Description = "Tá portando hein.",
                            Name = "O Gourmet"
                        },
                        new
                        {
                            AchievementId = 4,
                            Criteria = "Completar 5 pedidos sem cancelamento",
                            Description = "Palmas! O mínimo virou conquista.",
                            Name = "Sem Calote!"
                        },
                        new
                        {
                            AchievementId = 5,
                            Criteria = "Comprar pelo menos 1 de cada sabor disponível",
                            Description = "Eai, já decidiu qual o melhor?",
                            Name = "Caçador de Sabores"
                        },
                        new
                        {
                            AchievementId = 6,
                            Criteria = "Realizar compras em 7 dias diferentes",
                            Description = "Voltou pra comprar mais bolo 7 vezes. Vício tem outro nome.",
                            Name = "Fidelidade Doce"
                        },
                        new
                        {
                            AchievementId = 7,
                            Criteria = "Comprar 50 bolos cumulativamente",
                            Description = "50 bolos. Sério, parabéns.",
                            Name = "Bolo Master"
                        },
                        new
                        {
                            AchievementId = 8,
                            Criteria = "Nenhuma troca em 10 pedidos",
                            Description = "Impressionante.",
                            Name = "Evita Trocas"
                        },
                        new
                        {
                            AchievementId = 9,
                            Criteria = "Comprar bolos com promoções ou sabores surpresa",
                            Description = "Comprou bolo surpresa. Corajoso ou inconsequente? Nunca saberemos.",
                            Name = "Rei do Bolo Surpresa"
                        },
                        new
                        {
                            AchievementId = 11,
                            Criteria = "Deixou de pagar 1 pedido",
                            Description = "Não pagou o pedido. Espero que o boleto pelo menos estava gostoso.",
                            Name = "Caloteiro!"
                        },
                        new
                        {
                            AchievementId = 12,
                            Criteria = "Realizou 5 ou mais trocas de bolo",
                            Description = "Não é o que parece...",
                            Name = "Troca-Troca"
                        },
                        new
                        {
                            AchievementId = 13,
                            Criteria = "Comprar 5 bolos dos sabores: fubá com goiabada, queijadinha, fubá com doce de leite ou fubá cremoso",
                            Description = "Ninguem vai te culpar, sabores mineiros são os melhores",
                            Name = "Trem Bão!"
                        },
                        new
                        {
                            AchievementId = 14,
                            Criteria = "Comprar o bolo 'Luiz Felipe'",
                            Description = "Tá né...",
                            Name = "Luiz Felipe"
                        },
                        new
                        {
                            AchievementId = 15,
                            Criteria = "Comprar todos os bolos do cardápio pelo menos 1 vez",
                            Description = "Como é amigo?",
                            Name = "Mestre Confeiteiro"
                        },
                        new
                        {
                            AchievementId = 16,
                            Criteria = "Comprar bolo com cobertura adicional",
                            Description = "Pediu bolo com cobertura… herói",
                            Name = "Cobertura Extra"
                        },
                        new
                        {
                            AchievementId = 17,
                            Criteria = "Comprar bolo funcional/diet",
                            Description = "O Rafael tá sabendo disso?",
                            Name = "Saudável & Doce"
                        },
                        new
                        {
                            AchievementId = 18,
                            Criteria = "Comprar sabor fora do cardápio",
                            Description = "Comprou um sabor que nem está no cardápio… corajoso ou inconsequente? Talvez os dois.",
                            Name = "Rebelde da Confeitaria"
                        },
                        new
                        {
                            AchievementId = 19,
                            Criteria = "Comprar o sabor mais votado da semana",
                            Description = "Escolheu o sabor mais votado da semana… sem criatividade, mas pelo menos acertou.",
                            Name = "Seguidor de Multidões"
                        });
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Achievements.UserAchievement", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserAchievementId"));

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Flavors.Flavor", b =>
                {
                    b.Property<int>("FlavorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlavorId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("FlavorId");

                    b.ToTable("Flavors");

                    b.HasData(
                        new
                        {
                            FlavorId = 1,
                            Category = "Simples",
                            Description = "Massa de fubá com toque de limão siciliano.",
                            Name = "Fubá com Limão Siciliano",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 2,
                            Category = "Simples",
                            Description = "Combinação de maçã e castanhas.",
                            Name = "Maçã com Castanha",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 3,
                            Category = "Simples",
                            Description = "Massa de fubá com pedaços de goiabada.",
                            Name = "Fubá com Goiabada",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 4,
                            Category = "Simples",
                            Description = "Clássico bolo de fubá.",
                            Name = "Fubá",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 5,
                            Category = "Simples",
                            Description = "Bolo de milho com sabor tradicional.",
                            Name = "Milho",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 6,
                            Category = "Simples",
                            Description = "Bolo leve com sabor de iogurte.",
                            Name = "Iogurte",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 7,
                            Category = "Simples",
                            Description = "Bolo de fubá com textura cremosa.",
                            Name = "Fubá Cremoso",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 8,
                            Category = "Simples",
                            Description = "Bolo de cenoura fofinho.",
                            Name = "Cenoura",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 9,
                            Category = "Simples",
                            Description = "Massa de chocolate com granulado.",
                            Name = "Formigueiro",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 10,
                            Category = "Simples",
                            Description = "Combinação de banana e canela.",
                            Name = "Banana com Canela",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 11,
                            Category = "Caro",
                            Description = "Bolo de milho com recheio de requeijão.",
                            Name = "Milho com Requeijão",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 12,
                            Category = "Caro",
                            Description = "Bolo de cenoura com creme de avelã.",
                            Name = "Bolo de Cenoura com Creme de Avelã",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 13,
                            Category = "Caro",
                            Description = "Camadas de bolo de chocolate com leite condensado.",
                            Name = "Bolo Piscina de Chocolate com Leitinho",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 14,
                            Category = "Caro",
                            Description = "Camadas de bolo de milho com curau.",
                            Name = "Bolo Piscina de Milho com Curau",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 15,
                            Category = "Caro",
                            Description = "Camadas de bolo de goiabada e queijo.",
                            Name = "Bolo Piscina Romeu e Julieta",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 16,
                            Category = "Simples",
                            Description = "Bolo de cenoura com gotas de chocolate.",
                            Name = "Cenoura com Gotas de Chocolate",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 17,
                            Category = "Simples",
                            Description = "Bolo de mandioca com toque de queijo.",
                            Name = "Mandioca",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 18,
                            Category = "Simples",
                            Description = "Bolo de iogurte com limão.",
                            Name = "Iogurte com Limão",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 19,
                            Category = "Simples",
                            Description = "Massa de fubá com aroma de erva-doce.",
                            Name = "Fubá com Erva-Doce",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 20,
                            Category = "Simples",
                            Description = "Bolo de chocolate clássico.",
                            Name = "Chocolate",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 21,
                            Category = "Simples",
                            Description = "Bolo com sabor de coco.",
                            Name = "Coco",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 22,
                            Category = "Simples",
                            Description = "Bolo com sabor de laranja.",
                            Name = "Laranja",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 23,
                            Category = "Simples",
                            Description = "Bolo com sabor de limão.",
                            Name = "Limão",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 24,
                            Category = "Simples",
                            Description = "Bolo com sabor de maracujá.",
                            Name = "Maracujá",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 25,
                            Category = "Simples",
                            Description = "Bolo com mistura de sabores.",
                            Name = "Mesclado",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 26,
                            Category = "Simples",
                            Description = "Bolo fofinho de chocolate.",
                            Name = "Fofinho Chocolate",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 27,
                            Category = "Simples",
                            Description = "Bolo fofinho de fubá com laranja.",
                            Name = "Fofinho Fubá com Laranja",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 28,
                            Category = "Caro",
                            Description = "Bolo com sabor de leite condensado.",
                            Name = "Leitinho",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 29,
                            Category = "Caro",
                            Description = "Bolo com coco e chocolate.",
                            Name = "Prestígio",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 30,
                            Category = "Caro",
                            Description = "Bolo com sabor suave e fofinho.",
                            Name = "Toalha Felpuda",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 31,
                            Category = "Caro",
                            Description = "Bolo com sabor de amendoim.",
                            Name = "Amendoim",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 32,
                            Category = "Caro",
                            Description = "Bolo com damasco, nozes e uvas passas.",
                            Name = "Amizade",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 33,
                            Category = "Caro",
                            Description = "Bolo estilo brownie.",
                            Name = "Browie",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 34,
                            Category = "Caro",
                            Description = "Brownie com pedaços de nozes.",
                            Name = "Brownie com Nozes",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 35,
                            Category = "Simples",
                            Description = "Bolo com sabor de ameixa.",
                            Name = "Ameixa",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 36,
                            Category = "Simples",
                            Description = "Bolo de trigo simples.",
                            Name = "Trigo",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 37,
                            Category = "Simples",
                            Description = "Bolo com pedaços de maçã.",
                            Name = "Maçã",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 38,
                            Category = "Simples",
                            Description = "Bolo com sabor de queijo.",
                            Name = "Queijo",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 39,
                            Category = "Simples",
                            Description = "Bolo de fubá com crocância e laranja.",
                            Name = "Crocante Fubá com Laranja",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 40,
                            Category = "Caro",
                            Description = "Bolo com leite de coco e queijo parmesão.",
                            Name = "Luiz Felipe",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 41,
                            Category = "Caro",
                            Description = "Bolo com coco e queijo.",
                            Name = "Queijadinha",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 42,
                            Category = "Caro",
                            Description = "Bolo especial para o Natal.",
                            Name = "Natal",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 43,
                            Category = "Caro",
                            Description = "Bolo com camada de pudim.",
                            Name = "Bolo Pudim",
                            Votes = 0
                        },
                        new
                        {
                            FlavorId = 44,
                            Category = "Simples",
                            Description = "Bolo com sabor de café.",
                            Name = "Capuccino",
                            Votes = 0
                        });
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Pairs.Pair", b =>
                {
                    b.Property<int>("PairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PairId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer");

                    b.Property<int>("UserId2")
                        .HasColumnType("integer");

                    b.HasKey("PairId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("Pairs");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Purchases.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("Flavor1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Flavor2Id")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduleId1")
                        .HasColumnType("integer");

                    b.HasKey("PurchaseId");

                    b.HasIndex("Flavor1Id");

                    b.HasIndex("Flavor2Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ScheduleId1");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Schedules.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<bool>("Confirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PairId")
                        .HasColumnType("integer");

                    b.Property<int?>("PairId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekRef")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleId");

                    b.HasIndex("PairId");

                    b.HasIndex("PairId1");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Swaps.Swap", b =>
                {
                    b.Property<int>("SwapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SwapId"));

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SourceScheduleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING");

                    b.Property<int>("TargetScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("SwapId");

                    b.HasIndex("SourceScheduleId");

                    b.HasIndex("TargetScheduleId");

                    b.ToTable("Swaps");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Votes.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoteId"));

                    b.Property<int>("FlavorId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekRef")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VoteId");

                    b.HasIndex("FlavorId");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Achievements.UserAchievement", b =>
                {
                    b.HasOne("BakeItCountApi.Cn.Achievements.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Pairs.Pair", b =>
                {
                    b.HasOne("BakeItCountApi.Cn.Users.User", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Users.User", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Purchases.Purchase", b =>
                {
                    b.HasOne("BakeItCountApi.Cn.Flavors.Flavor", "Flavor1")
                        .WithMany()
                        .HasForeignKey("Flavor1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Flavors.Flavor", "Flavor2")
                        .WithMany()
                        .HasForeignKey("Flavor2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Schedules.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Schedules.Schedule", null)
                        .WithMany("Purchases")
                        .HasForeignKey("ScheduleId1");

                    b.Navigation("Flavor1");

                    b.Navigation("Flavor2");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Schedules.Schedule", b =>
                {
                    b.HasOne("BakeItCountApi.Cn.Pairs.Pair", "Pair")
                        .WithMany()
                        .HasForeignKey("PairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Pairs.Pair", null)
                        .WithMany("Schedules")
                        .HasForeignKey("PairId1");

                    b.Navigation("Pair");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Swaps.Swap", b =>
                {
                    b.HasOne("BakeItCountApi.Cn.Schedules.Schedule", "SourceSchedule")
                        .WithMany()
                        .HasForeignKey("SourceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Schedules.Schedule", "TargetSchedule")
                        .WithMany()
                        .HasForeignKey("TargetScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSchedule");

                    b.Navigation("TargetSchedule");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Votes.Vote", b =>
                {
                    b.HasOne("BakeItCountApi.Cn.Flavors.Flavor", "Flavor")
                        .WithMany()
                        .HasForeignKey("FlavorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BakeItCountApi.Cn.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flavor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Pairs.Pair", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BakeItCountApi.Cn.Schedules.Schedule", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
